---
- hosts: linuxenvanter
  gather_facts: false
  become: yes

  tasks:

   - shell: cat /etc/audit/auditd.conf
     register: auditd_contents

   - meta: end_play
     when: auditd_contents.stdout.find('max_log_file_action = keep_logs') != -1

   - name: Ansible insert lineinfile example
     lineinfile:
       dest: /etc/audit/auditd.conf
       line: max_log_file_action = rotate
       state: absent

   - name: Audit log compliance
     shell: | 
       echo "max_log_file_action = keep_logs" >> /etc/audit/auditd.conf

   - name: Restart auditd service
     service:
       name: auditd
       state: restarted
       enabled: yes

