---
- hosts: linuxenvanter
  gather_facts: false
  become: yes

  tasks:
 
   - shell: cat /etc/issue
     register: issue_contents

   - meta: end_play
     when: issue_contents.stdout.find('!!!DIKKAT!!!') != -1

   - name: Ansible delete /etc/issue file
     shell: echo  > /etc/issue


   - name: insert  configuration block in /etc/issue
     blockinfile:
       path: /etc/issue

       block: |
         !!!DIKKAT!!!
         * * * * * *
         Sincerely

