---
- hosts: linuxenvanter
  gather_facts: false
  become: yes

  tasks:
 
   - shell: cat /etc/motd
     register: motd_contents

   - meta: end_play
     when: motd_contents.stdout.find('Ansible') != -1

   - name: Ansible delete /etc/motd file
     shell: echo  > /etc/motd
          


   - name: insert  configuration block in /etc/motd
     blockinfile:
       path: /etc/motd

       block: |
         This server is managed by Ansible  centrally.
         If you have an user that has sudo right, with "sudo su -" command, you can easily pass to root user. 

         .         
 
