- hosts: linuxenvanter
  gather_facts: false
  
  tasks:

   - name: Stop service firewalld, if started
     service:
       name: firewalld
       state: stopped
       enabled: no

   - name: disable selinux
     selinux:
       state: disabled

   - name: Selinux disable permanently 
     replace:
       path: /etc/selinux/config
       regexp: '(\s+)SELINUX=enabled'
       replace: '\1SELINUX=disabled\2'
       backup: yes
