---
- hosts: linuxenvanter
  gather_facts: false
  become: yes

  tasks:
 
   - shell: cat /etc/pam.d/system-auth
     register: auth_contents

   - meta: end_play
     when: auth_contents.stdout.find('pam_pwquality.so minlen=8 lcredit=-1 ucredit=-1 dcredit=-1 ocredit=-1') != -1
     
   - name: Purge file
     shell: echo > /etc/pam.d/system-auth

   - name: insert configuration block in /etc/pam.d/system-auth
     blockinfile:
       path: /etc/pam.d/system-auth
       block: |
        auth        required      pam_env.so
        auth        required      pam_faildelay.so delay=2000000
        auth        sufficient    pam_fprintd.so
        auth        sufficient    pam_unix.so nullok try_first_pass
        auth        requisite     pam_succeed_if.so uid >= 1000 quiet_success
        auth        required      pam_deny.so

        account     required      pam_unix.so
        account     sufficient    pam_localuser.so
        account     sufficient    pam_succeed_if.so uid < 1000 quiet
        account     required      pam_permit.so

        password    requisite     pam_pwquality.so minlen=8 lcredit=-1 ucredit=-1 dcredit=-1 ocredit=-1
        password    sufficient    pam_unix.so sha512 shadow nullok try_first_pass use_authtok
        password    required      pam_deny.so

        session     optional      pam_keyinit.so revoke
        session     required      pam_limits.so
        session     optional      pam_systemd.so
        session     [success=1 default=ignore] pam_succeed_if.so service in crond quiet use_uid
        session     required      pam_unix.so
        auth        sufficient    pam_unix.so remember=5
 
